### ISSUE TITLE
Get rave working with TopCoat css

### ISSUE THREAD

**Issue by unscriptable** [RaveJS/rave#12]
For @fabricematrat. :)

**Comment by fabricematrat** [comment]
Thanks :)

**Comment by unscriptable** [comment]
This seems to work for me.  Because of the way TopCoat arranges its files, the module names are very ugly, unfortunately.  Somebody needs to create a topcoat-oocss repo! :)

**Comment by unscriptable** [comment]
I'm leaning towards inuitless, atm.  Gonna close this until I have time to work on either.  Reopen it if you want to work on it @fabricematrat. :)
