### ISSUE TITLE
Devise a way to help devs when they forget to use the `--save` option with npm or bower

### ISSUE THREAD

**Issue by unscriptable** [RaveJS/rave#20]
Problem: I just spent 15 minutes trying to figure out why my packages weren't loading.  Also, because one of those packages was rave, I was getting a cryptic error message when trying to use the rave() repl.

Options:
1. Lobby heavily with bower and npm to make `--save` the default.
2. Give up on rave's discover-at-run-time process and become a build-time tool.
3. Add a rave cli that always does the right thing.
4. ???

**Comment by unscriptable** [comment]
It seems like option 1 would be hard.  There are so many strong opinions and use cases in the package management world.

Option 2 just makes me sad.  

Option 3 seems to have additional benefits, so I'm liking it so far.  `rave install wire` could 
- check both package managers for "wire", 
- check if the user prefers bower or npm (by the presence of a package.json or bower.json or potentially via a config option), 
- warn the user to create a package.json or bower.json file first
- judge the suitability of the package by inspecting its metadata and/or provide warnings to the user ("Warning, this package is missing a moduleType attribute.")
- etc.

**Comment by phated** [comment]
Option 4: better error messages.  Option 1 would be hard but not impossible, option 2 is a waste of time, option 3 makes me even more sad (https://xkcd.com/927/)

**Comment by scothis** [comment]
If you have a runtime REPL, just have it compare what's on disk to whats in the manifest. If there's a discrepancy, notify the user.

Postel's Law applies here.

**Comment by unscriptable** [comment]
"what's on disk" hahahahah

**Comment by scothis** [comment]
Is the REPL in a browser? I assumed it was in node...

**Comment by unscriptable** [comment]
> Is the REPL in a browser?

Yep. :)

**Comment by scothis** [comment]
OK, I really need a rave demo at jsconf

**Comment by unscriptable** [comment]
@scothis: you'll never approach javascript projects the old way again.  :)

@phated: Ok, here's what's logged when a user forgets to specify --save (or for some other reason a package is not specified in either bower.json or package.json:

```
Unknown package when importing curl/domReady from experiments@0.1.6#experiments/write
Did you forget to specify `--save` when installing?
```

The ugly uid, "experiments@0.1.6#experiments/write", is unfortunate, atm, but it will be getting cleaner in a future release.  We may be able to add more useful info, too.  However, I'll have to do some refactoring of the debug module, first.  It's a real mess, atm.

I'll push this to master shortly.
