### ISSUE TITLE
Bower should not use package.json as an alternate metadata file

### ISSUE THREAD

**Issue by unscriptable** [RaveJS/rave#39]
Previously, we decided to use package.json as an alternate to bower.json when bower.json is missing.  In theory, this would have allowed devs to install packages that were published to bower without a bower.json.  In reality, this is problematic because the `dependencies` in package.json point to npm-specific packages, not bower packages.  The packages may not exist on bower or could be node-specific packages on npm.  

The only items we really care about in bower.json are `name` and `dependencies`.  `name` can be inferred from the requesting package (and/or directory name) and we can heuristically decide that there are no bower dependencies if there is no bower.json file.  

My guess is that this will fail less than the current strategy.

**Comment by KidkArolis** [comment]
what about main :-/

**Comment by unscriptable** [comment]
This issue is no longer relevant.  The core issue has been resolved in #40.
