### ISSUE TITLE
plugins aren't supported

### ISSUE THREAD

**Issue by phated** [RaveJS/rave#4]
AMD plugins are not supported.

**Comment by unscriptable** [comment]
dude! you're trying rave! woohoo!

I started looking into plugin support this weekend. It's tricky for plugins that have their own normalize function (eg has!, wire!). 

There are several major problems with the ES6 Loader spec. One of them prevents async normalization. I have some ideas to make it work (hacks), but in the short term, I can make simple plugins work.

**Comment by unscriptable** [comment]
Hey @phated,

We're thinking of supporting AMD plugins via rave extensions.  See #9.  This means you would have to create a rave extension to support your particular plugin(s).  Rave extensions are wicked easy to create.  I'll be creating some great reference examples in next few days.  You can also look at these working rave extensions now:  https://github.com/unscriptable/rave-load-text and https://github.com/unscriptable/rave-load-css

Thoughts?

-- J

**Comment by phated** [comment]
I am a little confused whether these are brand new modules that load things the same way that AMD plugins would, or are using the AMD plugins internally when an extension is resolved that matches the patterns.

**Comment by unscriptable** [comment]
These would be new packages and/or modules that are ES6 loader hooks that emulate AMD plugins. 

However, I hit some complications when trying to make the js! and link! plugins work. It may be just as easy to support a few, sane plugins by preloading them. Gonna look into that next.

**Comment by unscriptable** [comment]
@phated, forget what I said in github issue #9.  I created this instead: https://github.com/unscriptable/rave-amd-plugins  

rave-amd-plugins serves as a base for other rave extensions that will supply configuration and install necessary modules.  I'll create some documentation that shows how to make it work for other plugins, such as those in frozen. :)

**Comment by unscriptable** [comment]
I added some simple notes about creating an AMD plugin RaveJS extension to the README: https://github.com/unscriptable/rave-amd-plugins
