### ISSUE TITLE
Rave gives cryptic errors for missing modules ("fs" and "traceur") when app's moduleType is missing

### ISSUE THREAD

**Issue by unscriptable** [RaveJS/rave#56]
If the user doesn't specify a `moduleType` in the top-level bower.json file, rave gets loaded twice and ends up spewing cryptic error messages about not being able to load "fs" and "traceur".  This happened once before and seems to be a regression.

**Comment by KidkArolis** [comment]
I thought that was fixed by adding cjs module type detection. In other
words some moduleType is always detected and this error shouldn't be shown.
How do you reproduce this issue?

**Comment by unscriptable** [comment]
This is easy to reproduce.  Just clone and install rave-start as per the directions, then remove the moduleType property from bower.json.

I agree that moduleType detection is the way to go, but this problem is getting in the way! :)

**Comment by unscriptable** [comment]
Fixed as of 0.3.0! \o/
