### ISSUE TITLE
Allow devs to augment or override third-party packages' bower.json files

### ISSUE THREAD

**Issue by unscriptable** [RaveJS/rave#7]
Despite our attempts at crazy heuristics to guess the moduleType and main module of bower packages, we often don't guess correctly when they are missing (or the entire bower.json file is missing).  We need a simple way for devs to augment or override bower.json files.  

We should probably also allow this feature to override package.json files.

**Comment by unscriptable** [comment]
Idea 1: Put an "overrides" property in the app-level bower.json:

``` js
// bower.json
{
    "overrides": {
        "marked": {
            "moduleType": ["amd", "node", "globals"]
        }
    }
}
```

We may want to "namespace" this property.  "overrides" might be too common and I've already seen it used by gulp plugins.

**Comment by unscriptable** [comment]
Idea 2: Create an override file for each third-party package and specify it as a global option:

``` html
<html data-marked-meta="marked-overrides.json">
```

``` js
// marked-overrides.json
{
    "moduleType": ["amd", "node", "globals"]
}
```

**Comment by briancavalier** [comment]
I like idea 1, since if you have to do it for several packages (which may be the case until bower.json coverage grows more), the html attributes could get quite long.  The json would get long, too, but it seems less intrusive (and possible more expected) for json keys to grow.

Hmmm, what about:

``` html
<html data-rave-overrides="overrides.json">
```

``` json
{
    "marked": {
        "moduleType": ["amd", "node", "globals"]
    }
}
```

**Comment by unscriptable** [comment]
Idea (3) (Brian's idea) is very nice because it separates the exceptions from the normal metadata.  As a long-term solution, this is my favorite.  

However, in the short term (until the bower spec settles and package authors update to the final spec), almost all devs will have to specify overrides.  Therefore, idea (1) may have two minor advantages:
- 1 less configuration attribute on the `<html>` element
- 1 less file to load

Still not sure what is best. Need an :8ball:

**Comment by briancavalier** [comment]
+1 for simple.  I agree the most important thing in the short term is making it as easy as possible for people to deal with the overrides--it'll help rave adoption.  Then, once we get more feedback, we can think about doing something like 3.

**Comment by unscriptable** [comment]
Ok, so you said the word "simple".  So far, devs have not had to edit any metadata files directly.  They do, however, have to add html data-\* attrs.  This makes me wonder: is editing data-\* attrs the simplest possible thing?

**Comment by briancavalier** [comment]
I dunno, it seems like any solution that tried to only use data-\* attrs would get unweildy more quickly:

``` html
<html data-marked-overrides="{ moduleType: ['node'] }">
```

Hmm, now that I write it, it's not that bad :)  As long as the overrides stayed small, it'd be ok.  Feels weird to me tho.

**Comment by unscriptable** [comment]
Closed by #8.

**Comment by phated** [comment]
For servers that automatically generate an index page, the html-attribute-as-metadata would be really painful to work around.  Also, if that is the solution moving forward currently shouldn't the attributes be namespaced to rave, e.g. `data-rave-marked-overrides`

**Comment by briancavalier** [comment]
@phated Good points.  Check out #8, tho.  We went with a bower/npm "rave" property instead of html data attrs :)

**Comment by phated** [comment]
@briancavalier woot!

**Comment by unscriptable** [comment]
Yah, we know we need two ways to configure rave and rave extensions.  Hopefully, two will be enough! :)
